apiVersion: apps/v1
kind: Deployment
metadata:
  name: myubuntu-nginx
  namespace: myproject
  labels:
    app: myubuntu-nginx
    project: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myubuntu-nginx
  template:
    metadata:
      labels:
        app: myubuntu-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
